# Generated by Django 5.1.3 on 2024-12-24 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='country',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='firstname',
            new_name='dept',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='lastname',
            new_name='name',
        ),
        migrations.AddField(
            model_name='member',
            name='dof',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
